// The Glove grounding bridge — where the released peer card becomes the
// grounding source. This module is TRUST-CRITICAL; review it against
// jobpilot-saas/BRAND.md's non-fabrication promise before changing anything.
//
// Rules enforced here (see plan "The grounding rule, made precise"):
//  1. Only HUMAN-APPROVED material grounds: the released `peer_card` column
//     (written exclusively by POST /api/profile/approve) and the résumé text
//     snapshotted at release (`approved_cv_md`). Drafts and fetched caches
//     never reach this module's outputs.
//  2. The digest NEVER contains honest-gap terms. verifyGrounding hard-flags a
//     landmine only when the term is in the tailored CV and ABSENT from the
//     sources — printing "gaps: no PhD" into grounding text would let a
//     fabricated PhD sail through. Confirmed gaps flow into the landmine list
//     (effectiveLandmines) and the generation prompts (honestGapLabels), never
//     into grounding text.
//  3. File mode (the career-ops repo) stays byte-identical when no card is
//     released, and JOBPILOT_GROUNDING=files forces it back at any time.

import { getProfile } from '../db/index.js';
import { parseStoredCard, type PeerCard } from './peerCard.js';
import type { Profile } from '../types.js';

/** Escape-hatch: force file-based grounding even with a released card. */
function filesForced(): boolean {
  return process.env.JOBPILOT_GROUNDING === 'files';
}

/** The released card + approved CV, or null when the Glove doesn't ground. */
export function getReleasedCard(): { card: PeerCard; profile: Profile } | null {
  if (filesForced()) return null;
  const profile = getProfile();
  if (!profile) return null;
  const card = parseStoredCard(profile.peer_card);
  if (!card) return null;
  if (!(profile.approved_cv_md ?? '').trim()) return null;
  return { card, profile };
}

/** True when the released card is what grounds generation/verification. */
export function gloveActive(): boolean {
  return getReleasedCard() !== null;
}

/** YAML-escape a scalar: strip newlines/quotes, wrap in double quotes. */
function yamlScalar(value: string): string {
  return `"${value.replace(/[\r\n]+/g, ' ').replace(/"/g, "'").trim()}"`;
}

/** Emit `  key: "value"` lines for present values only (exact 2-space indent). */
function blockLines(pairs: Record<string, string | undefined>): string[] {
  return Object.entries(pairs)
    .filter((kv): kv is [string, string] => Boolean(kv[1]?.trim()))
    .map(([k, v]) => `  ${k}: ${yamlScalar(v)}`);
}

/**
 * Deterministic YAML from the released card's identity + policy.
 * Shape contract (round-trip tested against the REAL parsers):
 *  - `candidate:` / `location:` blocks with exactly-2-space children for
 *    src/apply/profile.ts readBlock (autofill identity).
 *  - `target_range` / `minimum` / `location_flexibility` keys findable by
 *    src/generate/fallback.ts yamlValue (offline fallback comp phrasing).
 */
export function synthesizeProfileYaml(card: PeerCard): string {
  const { identity, policy } = card;
  const lines: string[] = [
    '# Generated by Falkyr from the released peer card — edit the card, not this text.',
    'candidate:',
    ...blockLines({
      full_name: identity.fullName,
      email: identity.email,
      phone: identity.phone,
      location: identity.location,
      linkedin: identity.links.linkedin,
      github: identity.links.github,
      portfolio_url: identity.links.portfolio,
      twitter: identity.links.twitter,
    }),
  ];

  const loc = blockLines({ city: identity.city, country: identity.country });
  if (loc.length > 0) lines.push('location:', ...loc);

  const comp = blockLines({
    target_range: policy.compTarget,
    minimum: policy.compMinimum,
  });
  if (comp.length > 0) lines.push('compensation:', ...comp);

  if (policy.locationFlexibility?.trim()) {
    lines.push(`location_flexibility: ${yamlScalar(policy.locationFlexibility)}`);
  }
  if (policy.workAuthorization?.trim()) {
    lines.push(`work_authorization: ${yamlScalar(policy.workAuthorization)}`);
  }
  if (policy.noticePeriod?.trim()) {
    lines.push(`notice_period: ${yamlScalar(policy.noticePeriod)}`);
  }

  return lines.join('\n') + '\n';
}

/**
 * Deterministic markdown digest from the released card — the articleDigest
 * replacement. DELIBERATELY EXCLUDES the honestGaps section (rule 2 above);
 * a regression test asserts no confirmed gap term appears in this output.
 */
export function peerCardToDigest(card: PeerCard): string {
  const parts: string[] = [];

  if (card.identity.headline?.trim()) {
    parts.push(`# ${card.identity.fullName} — ${card.identity.headline}`);
  } else {
    parts.push(`# ${card.identity.fullName}`);
  }

  parts.push(
    '## How this candidate reads',
    ...card.archetypes.map(
      (a) => `- **${a.title}** (${a.strength}): ${a.why}`,
    ),
  );

  parts.push(
    '## Proof points',
    ...card.proofPoints.map((p) => {
      const metrics = p.metrics.length > 0 ? ` Figures: ${p.metrics.join(', ')}.` : '';
      return `- ${p.claim} — ${p.evidence}${metrics}`;
    }),
  );

  const voiceBits: string[] = [];
  if (card.voice.summary.trim()) voiceBits.push(card.voice.summary);
  if (card.voice.traits.length > 0) voiceBits.push(`Traits: ${card.voice.traits.join(', ')}.`);
  if (card.voice.avoid.length > 0) {
    voiceBits.push(`Would never say: ${card.voice.avoid.join('; ')}.`);
  }
  if (card.voice.sampleLines.length > 0) {
    voiceBits.push(...card.voice.sampleLines.map((l) => `> ${l}`));
  }
  if (voiceBits.length > 0) parts.push('## Voice', ...voiceBits);

  parts.push(
    '## Target',
    `Roles: ${card.huntingGrounds.targetTitles.join(' · ')}.`,
  );
  if (card.huntingGrounds.companyShapes.length > 0) {
    parts.push(`Company shapes: ${card.huntingGrounds.companyShapes.join(' · ')}.`);
  }
  if (card.huntingGrounds.seniority?.trim()) {
    parts.push(`Seniority: ${card.huntingGrounds.seniority}.`);
  }

  // NOTE: no honestGaps section here — see module header, rule 2.
  return parts.join('\n\n') + '\n';
}

/** Labels of confirmed gaps, for the generation prompts' never-claim block. */
export function honestGapLabels(card: PeerCard): string[] {
  return card.honestGaps.filter((g) => g.status === 'confirmed-gap').map((g) => g.label);
}

/**
 * Landmines for the verifier: the user's config landmines merged with the
 * released card's CONFIRMED gap terms ('have-it' and 'unsure' never merge).
 * Passes undefined through when nothing user-specific exists, so
 * verifyGrounding falls back to its DEFAULT_LANDMINES exactly as today.
 */
export function effectiveLandmines(
  configLandmines: readonly string[] | undefined,
): readonly string[] | undefined {
  const released = getReleasedCard();
  if (!released) return configLandmines;
  const cardTerms = released.card.honestGaps
    .filter((g) => g.status === 'confirmed-gap')
    .map((g) => g.term.toLowerCase());
  return [...new Set([...(configLandmines ?? []), ...cardTerms])];
}

/**
 * Title keywords for the scan. Precedence: released card > config file >
 * DEFAULT_KEYWORDS (handled by the caller's ?? chain). Card-first matters:
 * the shipped sources.config.json carries the owner's keywords — config-wins
 * would leave every Glove user scanning someone else's roles.
 */
export function cardTitleKeywords(): string[] | null {
  const released = getReleasedCard();
  if (!released) return null;
  const { targetTitles, keywords } = released.card.huntingGrounds;
  const merged = [...new Set([...targetTitles, ...keywords].map((k) => k.toLowerCase().trim()))];
  return merged.length > 0 ? merged : null;
}

/** Titles the card explicitly avoids (negative scan filter); [] when inactive. */
export function cardAvoidTitles(): string[] {
  const released = getReleasedCard();
  return released
    ? released.card.huntingGrounds.avoidTitles.map((t) => t.toLowerCase().trim())
    : [];
}
